rootProject.name = 'open-java-format-parent'

include ':gradle-open-java-format'
include ':open-java-format-eclipse-plugin'
include ':open-java-format-idea-plugin'
include ':open-java-format-spi'
include ':open-java-format'
include ':open-java-format-jdk-bootstrap'
include ':open-java-format-benchmarks'
include ':open-java-format-native'

boolean isCiServer = System.getenv().containsKey('CI')
buildCache {
    local {
        enabled = !isCiServer
    }
}
