apply plugin: 'java-library'

dependencies {
    api libs.guava
    api libs.jackson.annotations
    api libs.jackson.datatype.guava

    testImplementation libs.assertj
    testImplementation libs.junit.jupiter
    testImplementation libs.jackson.databind
}

javaVersion {
    target = 21
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
